# dataset
dataset : 
  name : Mydataset
  args : 
    root : ../../../data/BT_data/BT_data

# dataloader
dataloader : 
  args : 
    batch_size : 36
    shuffle : true
    num_workers : 6



##############################
#        autoencoder         #
##############################

# autoencoder optimizer
ae_optimizer : 
  name : Adam
  args : 
    lr : 1e-6
    betas : [0.9,0.999]
    weight_decay : 1e-6

# autoencoder lr sheduler
ae_lr_scheduler : 
  name : MultiStepLR
  args : 
    milestones : [50,100,150,200,250]
    gamma : 0.1

# autoencoder criterion
ae_criterion : 
  name : MSELoss

# autoencoder trainer
ae_trainer : 
  name : AETrainer
  args : 
    epoch : 1
    save_freq : 10000
    device : cuda:0


#############################
#       main model          #
#############################

# model optimizer
optimizer : 
  name : Adam
  args : 
    lr : 1e-6
    betas : [0.9,0.999]
    weight_decay : 1e-6

# lr scheduler
lr_scheduler : 
  name : MultiStepLR
  args : 
    milestones : [50,100]
    gamma : 0.1

# trainer
Trainer : 
  name : Trainer
  args : 
    epoch : 1
    save_freq : 10000
    device : cuda:0
    objective : one-class
    nu : 0.1 #Deep SVDD hyperparameter nu (must be 0 < nu <= 1).


#############################
#       Network conf        #
#############################

# Networks
networks : 
  base : 
    name : BTNet
    args : 
      in_channels : 3
      num_cnn : 3
      channels : [32,64,128]
      kernel_sizes : [5,5,5]
      paddings : [2,2,2]
      # strides : [1,1,1]
      rep_dim : 128
      linear : 32768
      acti_funcs : ['LeakyReLU','LeakyReLU','LeakyReLU']

  autoencoder : 
    name : BTAutoencoder
    args : 
      channels : [128,64,32]
      kernel_sizes : [4,4,4]
      paddings : [1,1,1]
      strides : [2,2,2]
      acti_funcs : ['LeakyReLU','LeakyReLU','LeakyReLU','Sigmoid']
      interpolate: [true, true,false]
